"""Cache the latest misoto22.com photographs as thumbnails and update the README strip.

Thumbnails are written to --out, which the profile workflow publishes to the
`output` branch; the README block links to them there. Needs Pillow:

    uv run --with pillow python scripts/photos.py --out dist
"""

import argparse
import html
import io
import json
import urllib.request
from pathlib import Path

from PIL import Image, ImageOps
from readme_block import replace_block

API_URL = "https://www.misoto22.com/api/photos?page_size={count}"
IMAGE_HOST = "https://images.misoto22.com/"
GALLERY_URL = "https://misoto22.com/photography"
RAW_URL = "https://raw.githubusercontent.com/Misoto22/Misoto22/output/{name}"
START_MARKER = "<!-- photos:start (generated by scripts/photos.py) -->"
END_MARKER = "<!-- photos:end -->"
THUMB_SIZE = 600  # square, so portrait and landscape frames line up in one row
MAX_DOWNLOAD = 20 * 1024 * 1024


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "Misoto22-profile"})
    with urllib.request.urlopen(request, timeout=60) as response:
        body = response.read(MAX_DOWNLOAD + 1)
    if len(body) > MAX_DOWNLOAD:
        raise ValueError(f"{url} is larger than {MAX_DOWNLOAD} bytes")
    return body


def latest_photos(count: int) -> list[dict[str, str]]:
    """Return title, place and source of the newest photos, validated."""
    results = json.loads(fetch(API_URL.format(count=count)))["results"]
    photos = []
    for item in results[:count]:
        src, title = item.get("src", ""), (item.get("title") or "").strip()
        # The API is outside this repository; only its own image host is fetched.
        if not src.startswith(IMAGE_HOST) or not title:
            raise ValueError(f"Unexpected photo record: {item!r}")
        photos.append(
            {"src": src, "title": title, "place": (item.get("place") or "").strip()}
        )
    if len(photos) < count:
        raise ValueError(f"Expected {count} photos, the API returned {len(photos)}")
    return photos


def save_thumbnail(source: bytes, target: Path) -> None:
    with Image.open(io.BytesIO(source)) as image:
        square = ImageOps.fit(
            image.convert("RGB"), (THUMB_SIZE, THUMB_SIZE), Image.LANCZOS
        )
        square.save(target, "JPEG", quality=82, optimize=True, progressive=True)


def render(photos: list[dict[str, str]]) -> str:
    cells = []
    for index, photo in enumerate(photos, start=1):
        label = ", ".join(part for part in (photo["title"], photo["place"]) if part)
        alt = html.escape(label, quote=True)
        src = RAW_URL.format(name=f"photo-{index}.jpg")
        cells.append(
            f'<a href="{GALLERY_URL}"><img src="{src}" alt="{alt}" title="{alt}" width="32%"></a>'
        )
    return '<p align="center">\n' + "\n".join(cells) + "\n</p>"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--count", default=3, type=int)
    parser.add_argument("--out", default="dist", type=Path)
    parser.add_argument("--readme", default="README.md", type=Path)
    args = parser.parse_args()

    photos = latest_photos(args.count)
    args.out.mkdir(parents=True, exist_ok=True)
    for index, photo in enumerate(photos, start=1):
        save_thumbnail(fetch(photo["src"]), args.out / f"photo-{index}.jpg")
    changed = replace_block(args.readme, START_MARKER, END_MARKER, render(photos))
    print(
        f"{len(photos)} thumbnails in {args.out}, README {'updated' if changed else 'unchanged'}"
    )


if __name__ == "__main__":
    main()
