"""Generate the Toolbox chips and the README block that lays them out.

Each tool is its own small SVG per theme, placed inline in the README so the
row wraps on a narrow screen instead of one wide image shrinking until its
text is unreadable. Icons come from Simple Icons (CC0), pinned so a rerun
reproduces the same output. Run from the repository root:

    python3 scripts/toolbox.py
"""

import argparse
import colorsys
import math
import re
import urllib.error
import urllib.request
from pathlib import Path

from readme_block import replace_block

ICON_URL = "https://cdn.jsdelivr.net/npm/simple-icons@{version}/icons/{slug}.svg"
ICON_VERSION = "16.32.0"
# Simple Icons later dropped these glyphs; pin the last release that shipped each.
PINNED_VERSIONS = {"openai": "15.22.0", "amazonwebservices": "14.15.0"}

# (row label, [(display name, simple-icons slug, brand hex)])
GROUPS = [
    (
        "Agents",
        [
            ("Claude Code", "claude", "D97757"),
            ("Codex", "openai", "000000"),
            ("Cursor", "cursor", "000000"),
            ("MCP", "modelcontextprotocol", "000000"),
            ("LangGraph", "langgraph", "7FC8FF"),
        ],
    ),
    (
        "Languages",
        [
            ("Python", "python", "3776AB"),
            ("TypeScript", "typescript", "3178C6"),
            ("Rust", "rust", "000000"),
            ("Swift", "swift", "F05138"),
            ("Bash", "gnubash", "4EAA25"),
        ],
    ),
    (
        "Frontend",
        [
            ("React", "react", "61DAFB"),
            ("Next.js", "nextdotjs", "000000"),
            ("Tailwind CSS", "tailwindcss", "06B6D4"),
            ("Vite", "vite", "9135FF"),
            ("Radix UI", "radixui", "161618"),
        ],
    ),
    (
        "Backend",
        [
            ("Django", "django", "092E20"),
            ("FastAPI", "fastapi", "009688"),
            ("Node.js", "nodedotjs", "5FA04E"),
            ("PostgreSQL", "postgresql", "4169E1"),
            ("SQLAlchemy", "sqlalchemy", "D71F00"),
            ("Redis", "redis", "FF4438"),
        ],
    ),
    (
        "Infra",
        [
            ("Docker", "docker", "2496ED"),
            ("GitHub Actions", "githubactions", "2088FF"),
            ("AWS", "amazonwebservices", "FF9900"),
            ("Cloudflare", "cloudflare", "F38020"),
            ("Vercel", "vercel", "000000"),
            ("Terraform", "terraform", "844FBA"),
        ],
    ),
]

START_MARKER = "<!-- toolbox:start (generated by scripts/toolbox.py) -->"
END_MARKER = "<!-- toolbox:end -->"

# GitHub Primer tokens, so the chips sit on the README like native UI.
THEMES = {
    "light": {
        "fg": "#1f2328",
        "muted": "#59636e",
        "chip": "#f6f8fa",
        "border": "#d1d9e0",
    },
    "dark": {
        "fg": "#f0f6fc",
        "muted": "#9198a1",
        "chip": "#151b23",
        "border": "#3d444d",
    },
}

# Arial advance widths (per 1000 em) for ASCII 32-126. Viewers render with the
# system UI font, so widths get SAFETY headroom instead of exact metrics.
ARIAL_WIDTHS = [
    278, 278, 355, 556, 556, 889, 667, 191, 333, 333, 389, 584, 278, 333, 278, 278,
    556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 584, 584, 584, 556,
    1015, 667, 667, 722, 722, 667, 611, 778, 722, 278, 500, 667, 556, 833, 722, 778,
    667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 278, 278, 278, 469, 556,
    333, 556, 556, 500, 556, 556, 278, 556, 556, 222, 222, 500, 222, 833, 556, 556,
    556, 556, 333, 500, 278, 556, 500, 722, 500, 500, 500, 334, 260, 334, 584,
]  # fmt: skip
SAFETY = 1.03

CHIP_HEIGHT = 32
MARGIN = 3  # transparent gutter, so wrapped rows never touch
LABEL_WIDTH = 104  # fixed, so every group's chips start in the same column
LABEL_SIZE = 11
ICON_SIZE = 16
FONT_SIZE = 13
FONT_STACK = (
    '-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif'
)


def text_width(text: str, size: float) -> float:
    units = sum(ARIAL_WIDTHS[ord(c) - 32] if 32 <= ord(c) < 127 else 600 for c in text)
    return units * size / 1000 * SAFETY


def fetch_icon(slug: str) -> str:
    """Return the single path of a Simple Icons glyph."""
    version = PINNED_VERSIONS.get(slug, ICON_VERSION)
    url = ICON_URL.format(version=version, slug=slug)
    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            svg = response.read().decode("utf-8")
    except urllib.error.HTTPError as error:
        raise ValueError(
            f"Simple Icons {version} has no glyph {slug!r}: {error}"
        ) from error
    match = re.search(r'<path d="([^"]+)"', svg)
    if match is None:
        raise ValueError(f"No path in Simple Icons glyph {slug!r}")
    return match.group(1)


def luminance(hex_color: str) -> float:
    def channel(value: int) -> float:
        c = value / 255
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = (int(hex_color.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)


def contrast(a: str, b: str) -> float:
    hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def icon_color(brand: str, theme: dict[str, str]) -> str:
    """Keep the brand's hue and saturation, moving only lightness until it reads (3:1).

    Black or white marks carry no hue to keep, so they take the text colour.
    """
    r, g, b = (int(brand[i : i + 2], 16) / 255 for i in (0, 2, 4))
    hue, light, sat = colorsys.rgb_to_hls(r, g, b)
    if sat < 0.1 or light < 0.02 or light > 0.98:
        return theme["fg"]
    toward_light = luminance(theme["chip"]) < 0.5
    for step in range(51):
        shift = step / 50
        lightness = light + (1 - light) * shift if toward_light else light * (1 - shift)
        rgb = colorsys.hls_to_rgb(hue, lightness, sat)
        candidate = "#" + "".join(f"{round(c * 255):02x}" for c in rgb)
        if contrast(candidate, theme["chip"]) >= 3:
            return candidate
    return theme["fg"]


def file_slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def render_chip(name: str, path: str, color: str, theme: dict[str, str]) -> str:
    """One tool as a standalone pill: icon, name, and a transparent margin."""
    chip_width = math.ceil(12 + ICON_SIZE + 8 + text_width(name, FONT_SIZE) + 12)
    width, height = chip_width + 2 * MARGIN, CHIP_HEIGHT + 2 * MARGIN
    icon_y = MARGIN + (CHIP_HEIGHT - ICON_SIZE) / 2
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" aria-label="{name}">'
        f"<title>{name}</title>"
        f'<rect x="{MARGIN + 0.5}" y="{MARGIN + 0.5}" width="{chip_width - 1}" '
        f'height="{CHIP_HEIGHT - 1}" rx="8" fill="{theme["chip"]}" '
        f'stroke="{theme["border"]}"/>'
        f'<path transform="translate({MARGIN + 12} {icon_y}) scale({ICON_SIZE / 24:.4f})" '
        f'fill="{color}" d="{path}"/>'
        f'<text x="{MARGIN + 12 + ICON_SIZE + 8}" y="{MARGIN + CHIP_HEIGHT / 2}" '
        f"dominant-baseline=\"central\" font-family='{FONT_STACK}' "
        f'font-size="{FONT_SIZE}" fill="{theme["fg"]}">{name}</text></svg>\n'
    )


def render_label(label: str, theme: dict[str, str]) -> str:
    """A group label drawn at chip height, so it lines up with the chips beside it."""
    text = label.upper()
    # Bold caps with letter spacing run wider than the regular-weight metrics.
    needed = text_width(text, LABEL_SIZE) * 1.1 + 0.08 * LABEL_SIZE * len(text)
    if needed > LABEL_WIDTH - 12:
        raise ValueError(f"Label {label!r} does not fit in {LABEL_WIDTH}px")
    height = CHIP_HEIGHT + 2 * MARGIN
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{LABEL_WIDTH}" height="{height}" '
        f'viewBox="0 0 {LABEL_WIDTH} {height}" role="img" aria-label="{label}">'
        f"<title>{label}</title>"
        f'<text x="1" y="{height / 2}" dominant-baseline="central" '
        f'font-family=\'{FONT_STACK}\' font-size="{LABEL_SIZE}" font-weight="600" '
        f'letter-spacing="{0.08 * LABEL_SIZE:.2f}" fill="{theme["muted"]}">{text}</text></svg>\n'
    )


def readme_block(assets: str) -> str:
    """The README markup: one row per group, its label then its chips, all inline."""
    groups = []
    for label, tools in GROUPS:
        chips = "\n".join(
            f'<picture><source media="(prefers-color-scheme: dark)" '
            f'srcset="./{assets}/dark/{file_slug(name)}.svg">'
            f'<img alt="{name}" src="./{assets}/light/{file_slug(name)}.svg"></picture>'
            for name, _, _ in tools
        )
        heading = (
            f'<picture><source media="(prefers-color-scheme: dark)" '
            f'srcset="./{assets}/dark/label-{file_slug(label)}.svg">'
            f'<img alt="{label}" src="./{assets}/light/label-{file_slug(label)}.svg"></picture>'
        )
        groups.append(f"<p>\n{heading}\n{chips}\n</p>")
    return "\n\n".join(groups)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default="assets/toolbox", type=Path)
    parser.add_argument("--readme", default="README.md", type=Path)
    args = parser.parse_args()

    icons = {slug: fetch_icon(slug) for _, tools in GROUPS for _, slug, _ in tools}
    for theme_name, theme in THEMES.items():
        folder = args.out / theme_name
        folder.mkdir(parents=True, exist_ok=True)
        for label, tools in GROUPS:
            label_svg = render_label(label, theme)
            (folder / f"label-{file_slug(label)}.svg").write_text(
                label_svg, encoding="utf-8"
            )
            for name, slug, brand in tools:
                svg = render_chip(name, icons[slug], icon_color(brand, theme), theme)
                (folder / f"{file_slug(name)}.svg").write_text(svg, encoding="utf-8")
    replace_block(
        args.readme, START_MARKER, END_MARKER, readme_block(args.out.as_posix())
    )
    count = sum(len(tools) for _, tools in GROUPS)
    print(
        f"wrote {count} chips x {len(THEMES)} themes to {args.out}, updated {args.readme}"
    )


if __name__ == "__main__":
    main()
