"""Generate the Toolbox chips and the README block that lays them out.

Each tool is its own small SVG per theme, all drawn at one width and placed
inline under a small centred label per group. Every group holds exactly four
tools, so a group is one full row on a desktop and a clean two-by-two on a
phone, never a row with one chip left over. Icons come from Simple Icons
(CC0), pinned so a rerun reproduces the same output. Run from the repository
root:

    python3 scripts/toolbox.py
"""

import argparse
import colorsys
import math
import re
import urllib.error
import urllib.request
from pathlib import Path

from readme_block import replace_block

ICON_URL = "https://cdn.jsdelivr.net/npm/simple-icons@{version}/icons/{slug}.svg"
ICON_VERSION = "16.32.0"
# Simple Icons later dropped these glyphs; pin the last release that shipped each.
PINNED_VERSIONS = {"openai": "15.22.0", "amazonwebservices": "14.15.0"}

# (group label, [(display name, simple-icons slug, brand hex)]); four per group.
GROUPS = [
    (
        "Agents",
        [
            ("Claude Code", "claude", "D97757"),
            ("Codex", "openai", "000000"),
            ("MCP", "modelcontextprotocol", "000000"),
            ("LangGraph", "langgraph", "7FC8FF"),
        ],
    ),
    (
        "Languages",
        [
            ("Python", "python", "3776AB"),
            ("TypeScript", "typescript", "3178C6"),
            ("Rust", "rust", "000000"),
            ("Swift", "swift", "F05138"),
        ],
    ),
    (
        "Frontend",
        [
            ("React", "react", "61DAFB"),
            ("Next.js", "nextdotjs", "000000"),
            ("Tailwind CSS", "tailwindcss", "06B6D4"),
            ("Vite", "vite", "9135FF"),
        ],
    ),
    (
        "Backend",
        [
            ("Django", "django", "092E20"),
            ("FastAPI", "fastapi", "009688"),
            ("PostgreSQL", "postgresql", "4169E1"),
            ("Redis", "redis", "FF4438"),
        ],
    ),
    (
        "Infra",
        [
            ("Docker", "docker", "2496ED"),
            ("GitHub Actions", "githubactions", "2088FF"),
            ("AWS", "amazonwebservices", "FF9900"),
            ("Cloudflare", "cloudflare", "F38020"),
        ],
    ),
]
GROUP_SIZE = 4
TOOLS = [tool for _, tools in GROUPS for tool in tools]

START_MARKER = "<!-- toolbox:start (generated by scripts/toolbox.py) -->"
END_MARKER = "<!-- toolbox:end -->"

# GitHub Primer tokens, so the chips sit on the README like native UI.
THEMES = {
    "light": {
        "fg": "#1f2328",
        "muted": "#59636e",
        "chip": "#f6f8fa",
        "border": "#d1d9e0",
    },
    "dark": {
        "fg": "#f0f6fc",
        "muted": "#9198a1",
        "chip": "#151b23",
        "border": "#3d444d",
    },
}

# Arial advance widths (per 1000 em) for ASCII 32-126. Viewers render with the
# system UI font, so widths get SAFETY headroom instead of exact metrics.
ARIAL_WIDTHS = [
    278, 278, 355, 556, 556, 889, 667, 191, 333, 333, 389, 584, 278, 333, 278, 278,
    556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 584, 584, 584, 556,
    1015, 667, 667, 722, 722, 667, 611, 778, 722, 278, 500, 667, 556, 833, 722, 778,
    667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 278, 278, 278, 469, 556,
    333, 556, 556, 500, 556, 556, 278, 556, 556, 222, 222, 500, 222, 833, 556, 556,
    556, 556, 333, 500, 278, 556, 500, 722, 500, 500, 500, 334, 260, 334, 584,
]  # fmt: skip
SAFETY = 1.03

CHIP_HEIGHT = 32
MARGIN = 2  # transparent gutter, so wrapped rows never touch
# Two chips plus the inline gap must fit GitHub's ~293px column on a phone.
MAX_CHIP_WIDTH = 138
LABEL_SIZE = 11
LABEL_HEIGHT = 20
ICON_SIZE = 16
FONT_SIZE = 13
FONT_STACK = (
    '-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif'
)


def text_width(text: str, size: float) -> float:
    units = sum(ARIAL_WIDTHS[ord(c) - 32] if 32 <= ord(c) < 127 else 600 for c in text)
    return units * size / 1000 * SAFETY


def fetch_icon(slug: str) -> str:
    """Return the single path of a Simple Icons glyph."""
    version = PINNED_VERSIONS.get(slug, ICON_VERSION)
    url = ICON_URL.format(version=version, slug=slug)
    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            svg = response.read().decode("utf-8")
    except urllib.error.HTTPError as error:
        raise ValueError(
            f"Simple Icons {version} has no glyph {slug!r}: {error}"
        ) from error
    match = re.search(r'<path d="([^"]+)"', svg)
    if match is None:
        raise ValueError(f"No path in Simple Icons glyph {slug!r}")
    return match.group(1)


def luminance(hex_color: str) -> float:
    def channel(value: int) -> float:
        c = value / 255
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = (int(hex_color.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)


def contrast(a: str, b: str) -> float:
    hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def icon_color(brand: str, theme: dict[str, str]) -> str:
    """Keep the brand's hue and saturation, moving only lightness until it reads (3:1).

    Black or white marks carry no hue to keep, so they take the text colour.
    """
    r, g, b = (int(brand[i : i + 2], 16) / 255 for i in (0, 2, 4))
    hue, light, sat = colorsys.rgb_to_hls(r, g, b)
    if sat < 0.1 or light < 0.02 or light > 0.98:
        return theme["fg"]
    toward_light = luminance(theme["chip"]) < 0.5
    for step in range(51):
        shift = step / 50
        lightness = light + (1 - light) * shift if toward_light else light * (1 - shift)
        rgb = colorsys.hls_to_rgb(hue, lightness, sat)
        candidate = "#" + "".join(f"{round(c * 255):02x}" for c in rgb)
        if contrast(candidate, theme["chip"]) >= 3:
            return candidate
    return theme["fg"]


def file_slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def natural_width(name: str) -> int:
    return math.ceil(12 + ICON_SIZE + 8 + text_width(name, FONT_SIZE) + 12)


def render_chip(
    name: str, path: str, color: str, theme: dict[str, str], chip_width: int
) -> str:
    """One tool as a standalone pill: icon, name, and a transparent margin.

    Icon and name are centred as a pair, so short names do not leave a gap.
    """
    width, height = chip_width + 2 * MARGIN, CHIP_HEIGHT + 2 * MARGIN
    icon_y = MARGIN + (CHIP_HEIGHT - ICON_SIZE) / 2
    content = ICON_SIZE + 8 + text_width(name, FONT_SIZE) / SAFETY
    icon_x = MARGIN + (chip_width - content) / 2
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" aria-label="{name}">'
        f"<title>{name}</title>"
        f'<rect x="{MARGIN + 0.5}" y="{MARGIN + 0.5}" width="{chip_width - 1}" '
        f'height="{CHIP_HEIGHT - 1}" rx="8" fill="{theme["chip"]}" '
        f'stroke="{theme["border"]}"/>'
        f'<path transform="translate({icon_x:.1f} {icon_y}) scale({ICON_SIZE / 24:.4f})" '
        f'fill="{color}" d="{path}"/>'
        f'<text x="{icon_x + ICON_SIZE + 8:.1f}" y="{MARGIN + CHIP_HEIGHT / 2}" '
        f"dominant-baseline=\"central\" font-family='{FONT_STACK}' "
        f'font-size="{FONT_SIZE}" fill="{theme["fg"]}">{name}</text></svg>\n'
    )


def render_label(label: str, theme: dict[str, str]) -> str:
    """A group label, centred in its own box so width estimates cannot skew it."""
    text = label.upper()
    spacing = 0.12 * LABEL_SIZE
    # Semibold caps run wider than the regular-weight metrics; pad generously.
    width = math.ceil(text_width(text, LABEL_SIZE) * 1.15 + spacing * len(text) + 16)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{LABEL_HEIGHT}" '
        f'viewBox="0 0 {width} {LABEL_HEIGHT}" role="img" aria-label="{label}">'
        f"<title>{label}</title>"
        f'<text x="{width / 2}" y="{LABEL_HEIGHT / 2}" text-anchor="middle" '
        f"dominant-baseline=\"central\" font-family='{FONT_STACK}' "
        f'font-size="{LABEL_SIZE}" font-weight="600" letter-spacing="{spacing:.2f}" '
        f'fill="{theme["muted"]}">{text}</text></svg>\n'
    )


def picture(assets: str, slug: str, alt: str) -> str:
    return (
        f'<picture><source media="(prefers-color-scheme: dark)" '
        f'srcset="./{assets}/dark/{slug}.svg">'
        f'<img alt="{alt}" src="./{assets}/light/{slug}.svg"></picture>'
    )


def readme_block(assets: str) -> str:
    """The README markup: per group, a centred label above its row of chips."""
    groups = []
    for label, tools in GROUPS:
        heading = picture(assets, f"label-{file_slug(label)}", label)
        chips = "\n".join(
            picture(assets, file_slug(name), name) for name, _, _ in tools
        )
        groups.append(f'<p align="center">\n{heading}<br>\n{chips}\n</p>')
    return "\n\n".join(groups)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default="assets/toolbox", type=Path)
    parser.add_argument("--readme", default="README.md", type=Path)
    args = parser.parse_args()

    uneven = [label for label, tools in GROUPS if len(tools) != GROUP_SIZE]
    if uneven:
        raise ValueError(f"Groups need exactly {GROUP_SIZE} tools each: {uneven}")
    chip_width = max(natural_width(name) for name, _, _ in TOOLS)
    if chip_width > MAX_CHIP_WIDTH:
        raise ValueError(
            f"Widest chip is {chip_width}px; phones fit {MAX_CHIP_WIDTH}px"
        )
    icons = {slug: fetch_icon(slug) for _, slug, _ in TOOLS}
    for theme_name, theme in THEMES.items():
        folder = args.out / theme_name
        folder.mkdir(parents=True, exist_ok=True)
        for label, _ in GROUPS:
            label_svg = render_label(label, theme)
            (folder / f"label-{file_slug(label)}.svg").write_text(
                label_svg, encoding="utf-8"
            )
        for name, slug, brand in TOOLS:
            color = icon_color(brand, theme)
            svg = render_chip(name, icons[slug], color, theme, chip_width)
            (folder / f"{file_slug(name)}.svg").write_text(svg, encoding="utf-8")
    replace_block(
        args.readme, START_MARKER, END_MARKER, readme_block(args.out.as_posix())
    )
    print(
        f"wrote {len(TOOLS)} chips x {len(THEMES)} themes at {chip_width}px "
        f"to {args.out}, updated {args.readme}"
    )


if __name__ == "__main__":
    main()
