"""Sync the README's Recent Writing list from the misoto22.com Atom feed.

Run from the repository root:

    python3 scripts/writing.py
"""

import argparse
import html
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path

from readme_block import replace_block

FEED_URL = "https://www.misoto22.com/feed.xml"
ATOM = "{http://www.w3.org/2005/Atom}"
ALLOWED_PREFIX = "https://misoto22.com/"
START_MARKER = "<!-- writing:start (generated by scripts/writing.py) -->"
END_MARKER = "<!-- writing:end -->"


def fetch_entries(url: str) -> list[tuple[datetime, str, str]]:
    """Return (published, title, link) for every post, newest first."""
    request = urllib.request.Request(url, headers={"User-Agent": "Misoto22-profile"})
    with urllib.request.urlopen(request, timeout=30) as response:
        body = response.read()
    try:
        root = ET.fromstring(body)
    except ET.ParseError as error:
        raise SystemExit(f"{url} is not a valid Atom feed: {error}") from error
    entries = []
    for entry in root.iter(f"{ATOM}entry"):
        title = (entry.findtext(f"{ATOM}title") or "").strip()
        stamp = entry.findtext(f"{ATOM}published") or entry.findtext(f"{ATOM}updated")
        link = next(
            (
                el.get("href", "")
                for el in entry.iter(f"{ATOM}link")
                if el.get("rel", "alternate") == "alternate"
            ),
            "",
        )
        # The feed is outside this repository; only its own posts may reach the README.
        if not title or not stamp or not link.startswith(ALLOWED_PREFIX):
            continue
        published = datetime.fromisoformat(stamp.replace("Z", "+00:00"))
        entries.append((published, title, link))
    return sorted(entries, reverse=True)


def render(entries: list[tuple[datetime, str, str]]) -> str:
    lines = []
    for published, title, link in entries:
        safe_title = (
            html.escape(title, quote=False).replace("[", "\\[").replace("]", "\\]")
        )
        lines.append(f"- [{safe_title}]({link}) <sub>{published:%b %Y}</sub>")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--feed", default=FEED_URL)
    parser.add_argument("--count", default=5, type=int)
    parser.add_argument("--readme", default="README.md", type=Path)
    args = parser.parse_args()

    entries = fetch_entries(args.feed)[: args.count]
    if not entries:
        # An empty feed is an outage, not an empty blog; keep the last good list.
        raise SystemExit(f"No posts found in {args.feed}; README left unchanged")
    changed = replace_block(args.readme, START_MARKER, END_MARKER, render(entries))
    print(f"{len(entries)} posts, README {'updated' if changed else 'unchanged'}")


if __name__ == "__main__":
    main()
